name: "Build Godot Deliverables"

on:
  push:
    branches: ["master", "main"]
  pull_request:
    branches: ["master", "main"]

jobs:
  build-windows:
    name: Build Windows
    runs-on: ubuntu-latest
    steps:
      - name: "Checkout Source Code"
        uses: actions/checkout@v4
      - name: "Export Windows Binary"
        uses: firebelley/godot-export@v5.2.0
        with:
          godot_version: 4.7.1
          export_preset: "Windows Desktop"